version: '3.8'

services:
  # Banco para Auth Service
  postgres-prontudigital:
    image: postgres:15
    container_name: postgres-prontudigital
    environment:
      POSTGRES_DB: prontudigital
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_prontudigital_data:/var/lib/postgresql/data

  prontudigital-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # REMOVER: ports - não expor para fora
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ARMAZENAMENTO_DIR=/dados/anexos
    depends_on:
      - postgres-prontudigital
    volumes:
      - anexos_prontudigital_data:/dados/anexos
    networks:
      - prontudigital-net

  # Gateway - ÚNICO com porta exposta
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - prontudigital-backend
    networks:
      - prontudigital-net

volumes:
  postgres_prontudigital_data:
  anexos_prontudigital_data:

networks:
  prontudigital-net:
    driver: bridge