# ============================================================
# Gateway — Desenvolvimento
# ============================================================
FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./

RUN ./mvnw dependency:go-offline -q

COPY src ./src

EXPOSE 9090

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
