spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: user_admin
    password: secret123
  flyway:
    url: jdbc:postgresql://localhost:5432/auth_db
    user: user_admin
    password: secret123
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

app:
  jwt:
    access-expiration-ms: 600000000
    refresh-expiration-ms: 600000000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-sroot-path: true  # Isso faz com que a raiz também acesse o swagger