spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/auth_db
    username: user_admin
    password: secret123
  flyway:
    url: jdbc:postgresql://postgres-auth:5432/auth_db
    user: user_admin
    password: secret123
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG