spring:
  application:
    name: auth-service
    profiles:
      active: develop
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    access-expiration-ms: 600000000
    refresh-expiration-ms: 600000000

# Configuração de segurança - aceitar apenas do gateway
server:
  forward-headers-strategy: framework

# Header de segurança para verificação interna
#security:
 # internal:
  #  secret: internal-auth-secret-123

logging:
  level:
    com.prontudigital.auth: DEBUG

cors:
  allowed-origins: "http://localhost:3000,http://localhost:3001"
