spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    access-expiration-ms: 10000
    refresh-expiration-ms: 600000000

logging:
  level:
    com.prontudigital.auth: DEBUG