spring:
  datasource:
    url: jdbc:postgresql://postgres-schedule:5433/schedule_db
    username: user_admin
    password: secret123
  flyway:
    url: jdbc:postgresql://postgres-schedule:5433/schedule_db
    user: user_admin
    password: secret123
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081

logging:
  level:
    org.flywaydb: DEBUG