spring:
  application:
    name: prontudigital

  datasource:
    url: jdbc:postgresql://localhost:5432/prontudigital
    username: user_admin
    password: secret123

  flyway:
    url: jdbc:postgresql://localhost:5432/prontudigital
    user: user_admin
    password: secret123
    locations: classpath:db/migracoes
    baseline-on-migrate: true

server:
  port: 8080

app:
  jwt:
    secret: "prontudigital-jwt-secret-key-for-hs512-authentication-2026-change-in-prod"
    access-expiration-ms: 600000000
    refresh-expiration-ms: 600000000
  notificacoes:
    habilitadas: true
    url-base-confirmacao: "http://localhost:8080/api/confirmacao"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springdoc: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: auth-service
        url: /v3/api-docs